DROP TABLE "MEDREC_OWNER"."ADMINISTRATORS";

DROP TABLE "MEDREC_OWNER"."OPENJPA_SEQUENCE_TABLE"; 

DROP TABLE "MEDREC_OWNER"."PATIENTS";

DROP TABLE "MEDREC_OWNER"."PATIENTS_RECORDS";

DROP TABLE "MEDREC_OWNER"."PHYSICIANS";

DROP TABLE "MEDREC_OWNER"."PRESCRIPTIONS";

DROP TABLE "MEDREC_OWNER"."DRUGS";

DROP TABLE "MEDREC_OWNER"."RECORDS";

DROP TABLE "MEDREC_OWNER"."RECORDS_PRESCRIPTIONS";
